# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2

jobs:

  build:
    working_directory: ~/cellphone_soft
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout

      - restore_cache:
        keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
        name: Install dependencies
        comand: npm install

      - save_cache:
        key: v1-npm-deps-{{ checksum "package-lock.json" }}
        paths:
            - ./node_modules
      - run:
        name: Build
        comand: npm run build


  deploy:
    machine:
      enabled: true
    steps:
    - run:
      name: Firebase Deploy
      command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
        requires:
          - hold
        filters:
          branches:
            only: master